name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Triggers on pull requests targeting the main branch

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Build the Sphinx documentation
      - name: Build Sphinx Documentation
        run: |
          sphinx-build -b html docs/source docs/build/html

      # Step 5: Deploy to GitHub Pages
      - name: Deploy Sphinx Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
